# Generated by Django 4.2.20 on 2025-04-20 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sells',
            name='product_price',
        ),
        migrations.AddField(
            model_name='sells',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.product'),
            preserve_default=False,
        ),
    ]
